org: nafiudanlawal
app: mmr-backend
service: mmr-backend
provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - Auth-Token
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http: 
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - Auth-Token
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false